backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "public/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog post" # Used in the UI
    folder: "data/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{publishDate}}_{{slug}}" # Filename template, e.g., YYYY-MM-DD-HH:MM_title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Original Publish Date", name: "publishDate", widget: "datetime", format: "YYYY-MM-DD", time_format: false}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {
          label: "Related Blog Posts",
          name: "related",
          widget: "list",
          max: 3,
          min: 0,
          field: {label: "Related Post", name: "relatedPost", widget: "relation", collection: "blog", searchFields: ["title"], valueField: "title"}
        }
