backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "public/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog post" # Used in the UI
    folder: "data/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{publishDate}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-HH:MM_title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Original Publish Date", name: "publishDate", widget: "datetime", format: "YYYY-MM-DD", time_format: false}
      - name: thumbnail
        label: Thumbnail Image
        widget: object
        fields:
          - {name: src, label: Image, widget: image}
          - {name: alt, label: Alt Text, widget: string}
          - {name: title, label: Title, widget: string}
      - name: heroImage
        label: Hero Image
        widget: object
        fields:
          - {name: src, label: Image, widget: image}
          - {name: alt, label: Alt Text, widget: string}
          - {name: title, label: Title, widget: string}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {
          label: "Related Blog Posts",
          name: "related",
          widget: "list",
          max: 3,
          min: 0,
          field: {label: "Related Post", name: "relatedPost", widget: "relation", collection: "blog", search_fields: ["title"], display_fields: ["title"], value_field: "{{slug}}"}
        }
  - name: "recipe"
    label: "Recipe post"
    folder: "data/recipe"
    create: true
    slug: "{{publishDate}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "recipe"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Original Publish Date", name: "publishDate", widget: "datetime", format: "YYYY-MM-DD", time_format: false}
      - name: thumbnail
        label: Thumbnail Image
        widget: object
        fields:
          - {name: src, label: Image, widget: image}
          - {name: alt, label: Alt Text, widget: string}
          - {name: title, label: Title, widget: string}
      - name: heroImage
        label: Hero Image
        widget: object
        fields:
          - {name: src, label: Image, widget: image}
          - {name: alt, label: Alt Text, widget: string}
          - {name: title, label: Title, widget: string}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Difficulty", name: "difficulty", widget: "select", options: ["Easy", "Medium", "Hard"]}
      - {label: "Time", name: "time", widget: "string"}
      - {label: "Servings", name: "servings", widget: "string"}
      - label: "Ingredients"
        name: "ingredients"
        widget: "list"
        fields:
          - label: "Ingredient"
            name: "ingredient"
            widget: "object"
            fields:
              - {label: "Amount", name: "amount", widget: "string"}
              - {label: "Name", name: "name", widget: "string"}
      - label: "Steps"
        name: "steps"
        widget: "list"
        fields:
          - {label: "Step", name: "step", widget: "text"}
      - {
          label: "Related Recipes",
          name: "related",
          widget: "list",
          max: 3,
          min: 0,
          field: {label: "Related Recipe", name: "relatedRecipe", widget: "relation", collection: "recipe", search_fields: ["title"], display_fields: ["title"], value_field: "{{slug}}"}
        }
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "homePage"
        file: "data/pages/homePage.md"
        fields:
          - label: "Hero"
            name: "hero"
            widget: "relation"
            collection: "recipe"
            search_fields: ["title"]
            value_field: "{{slug}}"
            display_fields: ["title"]
          - {
              label: "Featured Recipes",
              name: "featuredRecipes",
              widget: "list",
              max: 3,
              min: 0,
              field: {label: "Related Recipe", name: "relatedRecipe", widget: "relation", collection: "recipe", search_fields: ["title"], display_fields: ["title"], value_field: "{{slug}}"}
            }
      - label: "About Page"
        name: "aboutPage"
        file: "data/pages/aboutPage.md"
        fields:
          - {label: "Title", name: "title", widget: "text"}
          - name: heroImage
            label: Hero Image
            widget: object
            fields:
              - {name: src, label: Image, widget: image}
              - {name: alt, label: Alt Text, widget: string}
              - {name: title, label: Title, widget: string}
          - {label: "Body Text 1", name: "bodyText1", widget: "text"}
          - name: gridImage1
            label: Grid Image 1
            widget: object
            fields:
              - {name: src, label: Image, widget: image}
              - {name: alt, label: Alt Text, widget: string}
              - {name: title, label: Title, widget: string}
          - name: gridImage1
            label: Grid Image 2
            widget: object
            fields:
              - {name: src, label: Image, widget: image}
              - {name: alt, label: Alt Text, widget: string}
              - {name: title, label: Title, widget: string}
          - {label: "Body Text 2", name: "bodyText2", widget: "text"}
